# clippy.toml

# Minimum supported Rust version for your project
msrv = "1.70.0"

# Configures the threshold for the `too-large-for-stack` lint (in bytes)
too-large-for-stack = 512

# Set the maximum cognitive complexity allowed for a function
cognitive-complexity-threshold = 25

# Controls how many arguments a function can have before Clippy warns
too-many-arguments-threshold = 7

# Max allowed number of enum variants before Clippy suggests refactoring
enum-variant-name-threshold = 20

# Max number of struct fields before Clippy suggests breaking it up
type-complexity-threshold = 250

