# rustfmt.toml (stable-safe)

edition = "2021"
max_width = 100
use_small_heuristics = "Max"
wrap_comments = true
newline_style = "Unix"
control_brace_style = "AlwaysNextLine"
fn_params_layout = "Vertical"
match_block_trailing_comma = true
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_where_clauses = true
normalize_comments = true
normalize_doc_attributes = true
