[package]
name = "gen"
version = "0.1.0"
edition = "2021"
description = "The generation part of the project which implements how to mutate neural networks in a genetic algorithm"
license = "MIT"
repository = "https://github.com/mpohl100/ml_rust"
keywords = ["machine-learning", "rust", "neural-networks"]
categories = ["science", "machine-learning"]
readme = "../README.md"

[dependencies]
num-traits = "0.2"

alloc = { path = "../alloc" }
neural = { path = "../neural" }
evol = { path = "../evol" }