name: Build and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          env: |
            RUN_POSTCREATE=false
          runCmd: |
            # Add multiple commands to run if needed

            cargo build --release --verbose || exit 1
            cargo fmt --check || exit 1
            cargo clippy -- -D warnings || exit 1