name: Docs
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Clean docs folder
        run: cargo clean --doc
      - name: Build docs
        run: cargo doc --no-deps
      - name: Create workspace docs index
        run: |
          cat > target/doc/index.html <<'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Workspace Docs</title>
          </head>
          <body>
            <h1>Workspace Documentation</h1>
            <ul>
              <li><a href="alloc/index.html">alloc</a></li>
              <li><a href="app/index.html">app</a></li>
              <li><a href="gen/index.html">gen</a></li>
              <li><a href="neural/index.html">neural</a></li>
              <li><a href="regret/index.html">regret</a></li>
              <li><a href="utils/index.html">utils</a></li>
              <li><a href="evol/index.html">evol</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Remove lock file
        run: rm target/doc/.lock
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4